In [ ]:
 `/8import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/Social_Network_Ads - Social_Network_Ads.csv",
               usecols=['Age','EstimatedSalary','Purchased'])

In [ ]:
df.head(2)

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0

In [ ]:
x=df.drop(columns=['Purchased'])
y=df['Purchased']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()

In [ ]:
x_train_new=sc.fit_transform(x_train)

In [ ]:
x_test_new=sc.transform(x_test)

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier =GaussianNB()

In [ ]:
classifier.fit(x_train_new,y_train)

GaussianNB()

In [ ]:
y_pred=classifier.predict(x_test_new)

In [ ]:
y_pred

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
cn=confusion_matrix(y_test,y_pred)

In [ ]:
cn

array([[50,  2],
       [ 3, 25]])

In [ ]:
# [[tp, fp]
#  [fn ,tn]]

In [ ]:
from sklearn.metrics import accuracy_score


In [ ]:
accuracy_score(y_test,y_pred)

0.9375

In [ ]:
from sklearn.metrics import precision_score
# Assuming y_true and y_tred are true and predicted labels respectively
# or we can say in bewteen total positive prediction how many are true

precision=precision_score(y_test,y_pred)

In [ ]:
precision

0.9259259259259259

In [ ]:
from sklearn.metrics import recall_score
# Assuming y_true and y_pred are the true and predicted lables respectively

In [ ]:
recall=recall_score(y_test,y_pred)

In [ ]:
recall

0.8928571428571429

In [ ]:
from sklearn.metrics import f1_score
# in total number of positive prediction how many are right

In [ ]:
f1 = f1_score(y_test,y_pred)

In [ ]:
f1

0.9090909090909091

In [ ]:
# titanic, covid,credit

In [ ]:
df=pd.read_csv("/content/titanic - titanic.csv")

In [ ]:
df.head(2)

PassengerId  Survived  Pclass                              Name     Sex  \
0          892         0       3                  Kelly, Mr. James    male   
1          893         1       3  Wilkes, Mrs. James (Ellen Needs)  female   

    Age  SibSp  Parch  Ticket    Fare Cabin Embarked  
0  34.5      0      0  330911  7.8292   NaN        Q  
1  47.0      1      0  363272  7.0000   NaN        S

In [ ]:
df=df.drop(columns=['Name','Ticket','Cabin'])

In [ ]:
# df.dtypes

In [ ]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           1
Embarked       0
dtype: int64

In [ ]:
df['Fare']=df['Fare'].fillna(df['Fare'].mean())

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb=LabelEncoder()

In [ ]:
df['Sex']=lb.fit_transform(df['Sex'])

In [ ]:
df['Embarked']=lb.fit_transform(df['Embarked'])

In [ ]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_train_new=sc.fit_transform(x_train)
x_test_new=sc.fit_transform(x_test)

In [ ]:
classifier.fit(x_train_new,y_train)

GaussianNB()

In [ ]:
y_pred=classifier.predict(x_test_new)

In [ ]:
y_pred

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1])

In [ ]:
cn=confusion_matrix(y_test,y_pred)
cn

array([[50,  0],
       [ 0, 34]])

In [ ]:
accuracy_score(y_test,y_pred)

1.0

In [ ]:
precision_score(y_test,y_pred)

1.0

In [ ]:
recall=recall_score(y_test,y_pred)
recall

1.0

In [ ]:
f1 = f1_score(y_test,y_pred)
f1

1.0

In [ ]:
y_test

321    0
324    1
388    0
56     0
153    1
      ..
57     0
126    0
24     1
17     0
66     1
Name: Survived, Length: 84, dtype: int64

In [ ]:
y_pred

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1])

In [ ]:
df=pd.read_csv("/content/covid_toy - covid_toy.csv")

In [ ]:
df.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
df['gender']=lb.fit_transform(df['gender'])
df['cough']=lb.fit_transform(df['cough'])
df['city']=lb.fit_transform(df['city'])
df['has_covid']=lb.fit_transform(df['has_covid'])

In [ ]:
df['fever']=df['fever'].fillna(df['fever'].mean())

In [ ]:
x=df.drop(columns=['has_covid'])
y=df['has_covid']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_train_new=sc.fit_transform(x_train)
x_test_new=sc.fit_transform(x_test)

In [ ]:
classifier.fit(x_train_new,y_train)

GaussianNB()

In [ ]:
y_pred=classifier.predict(x_test_new)

In [ ]:
y_pred

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0])

In [ ]:
cn=confusion_matrix(y_test,y_pred)
cn

array([[10,  3],
       [ 4,  3]])

In [ ]:
accuracy_score(y_test,y_pred)

0.65

In [ ]:
f1_score(y_test,y_pred)

0.46153846153846156

In [ ]:
recall_score(y_test,y_pred)

0.42857142857142855

In [ ]:
precision_score(y_test,y_pred)

0.5

In [ ]:
df=pd.read_csv("/content/credit_scoring - credit_scoring.csv")

In [ ]:
df.head(3)

Age  Gender Marital Status Education Level Employment Status  \
0   60    Male        Married          Master          Employed   
1   25    Male        Married     High School        Unemployed   
2   30  Female         Single          Master          Employed   

   Credit Utilization Ratio  Payment History  Number of Credit Accounts  \
0                      0.22             2685                          2   
1                      0.20             2371                          9   
2                      0.22             2771                          6   

   Loan Amount  Interest Rate  Loan Term   Type of Loan  
0      4675000           2.65         48  Personal Loan  
1      3619000           5.19         60      Auto Loan  
2       957000           2.76         12      Auto Loan

In [ ]:
# df.isnull().sum()

In [ ]:
df['Type of Loan']=lb.fit_transform(df['Type of Loan'])

In [ ]:
df=pd.get_dummies(df,columns=['Gender','Marital Status','Education Level','Employment Status',])

In [ ]:
df=df.astype(int)

In [ ]:
# df.head(5)

In [ ]:
x=df.drop(columns=['Type of Loan'])
y=df['Type of Loan']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_train_new=sc.fit_transform(x_train)
x_test_new=sc.fit_transform(x_test)

In [ ]:
classifier.fit(x_train_new,y_train)

GaussianNB()

In [ ]:
y_pred=classifier.predict(x_test_new)
y_pred

array([0, 0, 1, 1, 1, 0, 0, 1, 2, 1, 1, 1, 2, 1, 1, 2, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 2, 1, 1, 1, 0, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 2, 1, 1, 1, 0, 0, 1, 0, 2, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 2, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 2, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1])

In [ ]:
cn=confusion_matrix(y_test,y_pred)
cn

array([[24, 50,  5],
       [18, 44,  1],
       [17, 37,  4]])

In [ ]:
accuracy_score(y_test,y_pred)

0.36

In [ ]:
f1_score(y_test,y_pred, average='weighted')

0.3143955493447939

In [ ]:
recall_score(y_test,y_pred, average='weighted')

0.36

In [ ]:
precision_score(y_test,y_pred, average='weighted')

0.38247949281925214